-- Decompiled using luadec 2.2 rev: 895d923 for Lua 5.1 from https://github.com/viruscamp/luadec
-- Command line: db 092023\as_db\lua\!InfrastructureShared\Unknowcategory\0x0000129a_luac 

-- params : ...
-- function num : 0
GetRuleInfo = function()
  -- function num : 0_0
  local l_1_0 = {}
  l_1_0.Name = "Block credential stealing from the Windows local security authority subsystem (lsass.exe)"
  l_1_0.Description = "Windows Defender Exploit Guard detected an attempt to extract credentials from LSASS."
  l_1_0.NotificationDedupingInterval = 14400
  l_1_0.NotificationDedupingScope = HIPS.DEDUPE_SCOPE_ALL
  return l_1_0
end

GetMonitoredLocations = function()
  -- function num : 0_1
  local l_2_0 = {}
  l_2_0["%windir%\\system32\\lsass.exe"] = 2
  return 7, l_2_0
end

GetPathExclusions = function()
  -- function num : 0_2
  local l_3_0 = {}
  l_3_0["%windir%\\system32\\WerFaultSecure.exe"] = 2
  l_3_0["%windir%\\system32\\mrt.exe"] = 2
  l_3_0["%windir%\\system32\\svchost.exe"] = 2
  l_3_0["%windir%\\system32\\NETSTAT.EXE"] = 2
  l_3_0["%windir%\\syswow64\\NETSTAT.EXE"] = 2
  l_3_0["%windir%\\system32\\wbem\\WmiPrvSE.exe"] = 2
  l_3_0["%windir%\\SysWOW64\\wbem\\WmiPrvSE.exe"] = 2
  l_3_0["%windir%\\system32\\DriverStore\\FileRepository\\*\\NVWMI\\nvWmi64.exe"] = 2
  l_3_0["%programfiles(x86)%\\Microsoft Intune Management Extension\\ClientHealthEval.exe"] = 2
  l_3_0["%programfiles(x86)%\\Microsoft Intune Management Extension\\SensorLogonTask.exe"] = 2
  l_3_0["%programfiles(x86)%\\Microsoft Intune Management Extension\\Microsoft.Management.Services.IntuneWindowsAgent.exe"] = 2
  l_3_0["%programdata%\\Microsoft\\Windows Defender Advanced Threat Protection\\DataCollection\\*\\OpenHandleCollector.exe"] = 2
  l_3_0["%programfiles%\\WindowsApps\\Microsoft.GamingServices_*\\gamingservices.exe"] = 2
  l_3_0["%programfiles(x86)%\\Cisco\\Cisco AnyConnect Secure Mobility Client\\vpnagent.exe"] = 2
  l_3_0["%programfiles(x86)%\\Zoom\\bin\\CptHost.exe"] = 2
  l_3_0["%programfiles(x86)%\\Microsoft\\EdgeUpdate\\MicrosoftEdgeUpdate.exe"] = 2
  l_3_0["%programfiles(x86)%\\Microsoft\\Edge\\Application\\*\\Installer\\setup.exe"] = 2
  l_3_0["%programfiles(x86)%\\Google\\Update\\GoogleUpdate.exe"] = 2
  l_3_0["%programfiles(x86)%\\Splunk\\bin\\splunkd.exe"] = 2
  l_3_0["%programfiles(x86)%\\Zscaler\\ZSAUpm\\ZSAUpm.exe"] = 2
  l_3_0["%programfiles(x86)%\\Fortinet\\FortiClient\\FortiESNAC.exe"] = 2
  l_3_0["%programfiles(x86)%\\FireEye\\xagt\\xagt.exe"] = 2
  l_3_0["%programfiles(x86)%\\Autodesk\\Autodesk Desktop App\\AdAppMgrSvc.exe"] = 2
  l_3_0["%programfiles(x86)%\\Dropbox\\Update\\DropboxUpdate.exe"] = 2
  l_3_0["%programfiles(x86)%\\HP\\HP Touchpoint Analytics Client\\Provider Data Sources\\ProcInfo\\ProcInfo.exe"] = 2
  l_3_0["%programfiles(x86)%\\Common Files\\Adobe\\AdobeGCClient\\AGMService.exe"] = 2
  l_3_0["%programfiles(x86)%\\Tanium\\Tanium Client\\Tools\\Detect3\\TaniumDetectEngine.exe"] = 2
  l_3_0["%programfiles(x86)%\\Airwatch\\AgentUI\\AWProcessCommands.exe"] = 2
  l_3_0["%programfiles(x86)%\\Bit9\\Parity Agent\\Parity.exe"] = 2
  l_3_0["%programfiles(x86)%\\Arctic Wolf Networks\\Agent\\ossec-agent.exe"] = 2
  l_3_0["%programfiles(x86)%\\Cordaware\\Infoband\\Infoclient.exe"] = 2
  l_3_0["%programfiles(x86)%\\Splunk\\bin\\splunk-regmon.exe"] = 2
  l_3_0["%programfiles(x86)%\\Lenovo\\VantageService\\*\\LenovoVantage-(LenovoBoostSystemAddin).exe"] = 2
  l_3_0["%programfiles(x86)%\\Micro Focus\\Discovery Agent\\bin32\\discagnt.exe"] = 2
  l_3_0["%programfiles(x86)%\\Hewlett-Packard\\Discovery Agent\\bin32\\discagnt.exe"] = 2
  l_3_0["%programfiles(x86)%\\Micro Focus\\Discovery Agent\\Plugins\\usage\\discusge.exe"] = 2
  l_3_0["%programfiles(x86)%\\Hewlett-Packard\\Discovery Agent\\Plugins\\usage\\discusge.exe"] = 2
  l_3_0["%programfiles(x86)%\\Cisco\\Cisco AnyConnect Secure Mobility Client\\aciseagent.exe"] = 2
  l_3_0["%programfiles(x86)%\\BigFix Enterprise\\BES Client\\BESClient.exe"] = 2
  l_3_0["%programfiles(x86)%\\Logitech\\LogiSync\\sync-agent\\LogiSyncHandler.exe"] = 2
  l_3_0["%programfiles(x86)%\\ManageSoft\\Tracker\\ndtrack.exe"] = 2
  l_3_0["%programfiles(x86)%\\Aternity Information Systems\\Agent"] = 2
  l_3_0["%programfiles(x86)%\\Cisco\\Cisco AnyConnect Secure Mobility Client\\vpndownloader.exe"] = 2
  l_3_0["%programfiles(x86)%\\Common Files\\Adobe\\ARM\\*\\AdobeARMHelper.exe"] = 2
  l_3_0["%programfiles(x86)%\\Common Files\\Adobe\\ARM\\*\\Temp\\*\\AdobeARMHelper.exe"] = 2
  l_3_0["%programfiles(x86)%\\Adobe\\Acrobat Reader DC\\Reader\\AcroCEF\\RdrServicesUpdater.exe"] = 2
  l_3_0["%programfiles(x86)%\\Aternity Information Systems\\Update\\AternityUpdate.exe"] = 2
  l_3_0["%programfiles(x86)%\\Tanium\\Tanium Client\\TaniumClient.exe"] = 2
  l_3_0["%programfiles(x86)%\\BraveSoftware\\Update\\BraveUpdate.exe"] = 2
  l_3_0["%programfiles(x86)%\\SysTrack\\LsiAgent\\LsiSupervisor\\*\\LsiSupervisor.exe"] = 2
  l_3_0["%programfiles(x86)%\\Cisco\\Cisco HostScan\\bin\\ciscod.exe"] = 2
  l_3_0["%programfiles(x86)%\\SysTrack\\LsiAgent\\LsiMods64.exe"] = 2
  l_3_0["%programfiles(x86)%\\CheckPoint\\Endpoint Connect\\Watchdog\\EPWD.exe"] = 2
  l_3_0["%programfiles(x86)%\\CheckPoint\\Endpoint Security\\Endpoint Common\\bin\\cpda.exe"] = 2
  l_3_0["%programfiles(x86)%\\VMware\\VMware Tools"] = 2
  l_3_0["%programfiles(x86)%\\VMware\\VMware Horizon View Client"] = 2
  l_3_0["%programfiles(x86)%\\Common Files\\VMware\\Remote Experience"] = 2
  l_3_0["%programfiles(x86)%\\Cisco\\Cisco AnyConnect Secure Mobility Client\\acswgagent.exe"] = 2
  l_3_0["%programfiles(x86)%\\N-able Technologies\\Windows Agent\\bin\\agent.exe"] = 2
  l_3_0["%programfiles(x86)%\\Digital Arts\\AC\\app\\bin\\acservice.exe"] = 2
  l_3_0["%programfiles(x86)%\\MOTEX\\LanScope Cat MR\\Lspcmr.exe"] = 2
  l_3_0["%programfiles(x86)%\\Power Automate Desktop\\Microsoft.Flow.RPA.LauncherService.exe"] = 2
  l_3_0["%programfiles(x86)%\\DesktopCentral_Agent\\bin\\dcagentservice.exe"] = 2
  l_3_0["%programfiles(x86)%\\CheckPoint\\Endpoint Security\\Endpoint Common\\bin\\IDAFServerHostService.exe"] = 2
  l_3_0["%programfiles(x86)%\\Arctic Wolf Networks\\Agent\\plugins\\osquery\\osqueryi.exe"] = 2
  l_3_0["%programfiles(x86)%\\Btc\\eAudytor\\eAgent\\Bin\\qati.exe"] = 2
  l_3_0["%programfiles(x86)%\\Adobe\\Adobe Sync\\CoreSync\\customhook\\CoreSyncCustomHook.exe"] = 2
  l_3_0["%programfiles(x86)%\\NetSupport\\NetSupport School"] = 2
  l_3_0["%programfiles(x86)%\\UEMS_Agent\\bin\\dcagentservice.exe"] = 2
  l_3_0["%programfiles(x86)%\\Google\\Temp\\*\\GoogleUpdate.exe"] = 2
  l_3_0["%programfiles(x86)%\\Adobe\\Acrobat DC\\Acrobat\\AcroCEF\\AcroServicesUpdater.exe"] = 2
  l_3_0["%programfiles(x86)%\\Ninite Agent\\NiniteAgent.exe"] = 2
  l_3_0["%programfiles(x86)%\\HP\\HP Classroom Manager\\Runplugin64.exe"] = 2
  l_3_0["%programfiles(x86)%\\SysTrack\\LsiAgent\\LsiAgent.exe"] = 2
  l_3_0["%programfiles(x86)%\\VMware\\VMware Player\\vmware-authd.exe"] = 2
  l_3_0["%programfiles(x86)%\\Dameware Remote Everywhere Agent\\BASupSysInf.exe"] = 2
  l_3_0["%programfiles(x86)%\\Power Automate Desktop\\Microsoft.Flow.RPA.*.exe"] = 2
  l_3_0["%programfiles(x86)%\\Common Files\\Adobe\\Adobe Desktop Common\\ElevationManager\\Adobe Installer.exe"] = 2
  l_3_0["%programfiles(x86)%\\Common Files\\Adobe\\Adobe Desktop Common\\HDBox\\Setup.exe"] = 2
  l_3_0["%programfiles(x86)%\\SolarWinds"] = 2
  l_3_0["%programfiles(x86)%\\checkmk\\service\\check_mk_agent.exe"] = 2
  l_3_0["%programfiles(x86)%\\ClassPolicyAgent\\PolicyAgent.exe"] = 2
  l_3_0["%programfiles(x86)%\\VMware\\VMware Workstation\\vmware-authd.exe"] = 2
  l_3_0["%programfiles(x86)%\\Cisco\\Cisco Secure Client\\vpnagent.exe"] = 2
  l_3_0["%programfiles(x86)%\\Balbix\\Update\\BalbixUpdate.exe"] = 2
  l_3_0["%programfiles(x86)%\\Bradford Networks\\Persistent Agent\\bndaemon.exe"] = 2
  l_3_0["%programfiles(x86)%\\Site24x7\\WinAgent\\monitoring\\bin\\MEAgentHelper.exe"] = 2
  l_3_0["%programfiles(x86)%\\Site24x7\\WinAgent\\monitoring\\bin\\AppBin\\Site24x7AppAgent.exe"] = 2
  l_3_0["%programfiles(x86)%\\Cato Networks\\Cato Client\\winvpnclient.cli.exe"] = 2
  l_3_0["%programfiles(x86)%\\ManageEngine\\UEMS_Agent\\bin\\dcagentservice.exe"] = 2
  l_3_0["%programfiles(x86)%\\Sky Product\\SKYSEA Client View\\CtlCli.exe"] = 2
  l_3_0["%programfiles(x86)%\\Tanium\\Tanium Client\\TaniumCX.exe"] = 2
  l_3_0["%programfiles(x86)%\\xagt\\xagt.exe"] = 2
  l_3_0["%programfiles(x86)%\\Microsoft Azure Site Recovery\\agent\\s2RCM.exe"] = 2
  l_3_0["%programfiles%\\Avecto\\Privilege Guard Client\\DefendpointService.exe"] = 2
  l_3_0["%programfiles%\\Intel\\SUR\\QUEENCREEK\\x64\\esrv_svc.exe"] = 2
  l_3_0["%programfiles%\\Microsoft Monitoring Agent\\Agent\\HealthService.exe"] = 2
  l_3_0["%programfiles%\\Microsoft Monitoring Agent\\Agent\\MOMPerfSnapshotHelper.exe"] = 2
  l_3_0["%programfiles%\\Nexthink\\Collector\\Collector\\nxtsvc.exe"] = 2
  l_3_0["%programfiles%\\Splunk\\bin\\splunkd.exe"] = 2
  l_3_0["%programfiles%\\Azure Advanced Threat Protection Sensor\\*\\Microsoft.Tri.Sensor.Updater.exe"] = 2
  l_3_0["%programfiles%\\common files\\microsoft shared\\ClickToRun\\Updates\\*\\OfficeClickToRun.exe"] = 2
  l_3_0["%programfiles%\\Zscaler\\ZSAUpm\\ZSAUpm.exe"] = 2
  l_3_0["%programfiles%\\Fortinet\\FortiClient\\FortiESNAC.exe"] = 2
  l_3_0["%programfiles%\\FireEye\\xagt\\xagt.exe"] = 2
  l_3_0["%programfiles%\\Autodesk\\Autodesk Desktop App\\AdAppMgrSvc.exe"] = 2
  l_3_0["%programfiles%\\Qualys\\QualysAgent\\QualysAgent.exe"] = 2
  l_3_0["%programfiles%\\Altiris\\Altiris Agent\\AeXNSAgent.exe"] = 2
  l_3_0["%programfiles%\\VMware\\VMware Tools"] = 2
  l_3_0["%programfiles%\\VMware\\VMware Horizon View Client"] = 2
  l_3_0["%programfiles%\\Common Files\\VMware\\Remote Experience"] = 2
  l_3_0["%programfiles%\\Dell\\DTP\\InstrumentationSubAgent\\Dell.TechHub.Instrumentation.SubAgent.exe"] = 2
  l_3_0["%programfiles%\\Rapid7\\Insight Agent\\components\\insight_agent\\*\\ir_agent.exe"] = 2
  l_3_0["%programfiles%\\Microsoft RDInfra\\RDMonitoringAgent_*\\Agent\\MonAgentCore.exe"] = 2
  l_3_0["%programfiles%\\BMCSoftware\\Client Management\\Client\\bin\\mtxagent.exe"] = 2
  l_3_0["%programfiles%\\DisplayLink Core Software\\DisplayLinkHotDeskService.exe"] = 2
  l_3_0["%programfiles%\\ManageSoft\\Tracker\\ndtrack.exe"] = 2
  l_3_0["%programfiles%\\Websense\\Websense Endpoint\\wepsvc.exe"] = 2
  l_3_0["%programfiles%\\Ricoh\\Streamline NX\\PC Client\\jre\\bin\\java.exe"] = 2
  l_3_0["%programfiles%\\Microsoft Monitoring Agent\\Agent\\Health Service State\\Resources\\*\\pmfexe.exe"] = 2
  l_3_0["%programfiles%\\Microsoft Monitoring Agent\\Agent\\MonitoringHost.exe"] = 2
  l_3_0["%programfiles%\\AppSense\\Application Manager\\Agent\\AMAgent.exe"] = 2
  l_3_0["%programfiles%\\Adobe\\Acrobat DC\\Acrobat\\AcroCEF\\SingleClientServicesUpdater.exe"] = 2
  l_3_0["%programfiles%\\osquery\\osqueryd\\osqueryd.exe"] = 2
  l_3_0["%programfiles%\\Microsoft OneDrive\\OneDriveStandaloneUpdater.exe"] = 2
  l_3_0["%programfiles%\\CyberArk\\Endpoint Privilege Manager\\Agent\\PASAgent\\PASAgent.exe"] = 2
  l_3_0["%programfiles%\\Palo Alto Networks\\GlobalProtect\\PanGPS.exe"] = 2
  l_3_0["%programfiles%\\Smart-X\\ControlUpAgent\\Version*\\cuAgent.exe"] = 2
  l_3_0["%programfiles%\\Citrix\\*\\XenDesktopRestApiService.exe"] = 2
  l_3_0["%programfiles%\\Palo Alto Networks\\DEM\\DEMAgentProcess.exe"] = 2
  l_3_0["%programfiles%\\Phantom\\IBSA\\ibsaService.exe"] = 2
  l_3_0["%programfiles%\\eGurkha\\lib\\AppPid.exe"] = 2
  l_3_0["%programfiles%\\dynatrace\\oneagent\\agent\\lib64\\oneagentos.exe"] = 2
  l_3_0["%programfiles%\\dynatrace\\oneagent\\agent\\lib64\\oneagentplugin.exe"] = 2
  l_3_0["%programfiles%\\Remote Desktop WebRTC Redirector\\MsRdcWebRTCSvc.exe"] = 2
  l_3_0["%programfiles%\\Sophos\\Sophos File Scanner\\SophosFileScanner.exe"] = 2
  l_3_0["%programfiles%\\NetSupport\\NetSupport School"] = 2
  l_3_0["%programfiles%\\OEM\\AMS\\Service\\ams.exe"] = 2
  l_3_0["%programfiles%\\Eracent\\EPM\\epm.exe"] = 2
  l_3_0["%programfiles%\\Cybereason ActiveProbe\\minionhost.exe"] = 2
  l_3_0["%programfiles%\\Google\\Temp\\*\\GoogleUpdate.exe"] = 2
  l_3_0["%programfiles%\\Orbit\\bin\\osqueryd\\windows\\stable\\osqueryd.exe"] = 2
  l_3_0["%programfiles%\\1E\\Client\\1E.Client.exe"] = 2
  l_3_0["%programfiles%\\Endgame\\esensor.exe"] = 2
  l_3_0["%programfiles%\\Microsoft Cloud Managed Desktop Extension\\CMDExtension\\Microsoft.Management.Services.CloudManagedDesktop.Agent.exe"] = 2
  l_3_0["%programfiles%\\common files\\microsoft shared\\ClickToRun\\OfficeClickToRun.exe"] = 2
  l_3_0["%programfiles%\\Adobe\\Adobe Creative Cloud Experience\\libs\\node.exe"] = 2
  l_3_0["%programfiles%\\Fortinet\\FortiClient\\FortiProxy.exe"] = 2
  l_3_0["%programfiles%\\Guardicore\\gc-launcher.exe"] = 2
  l_3_0["%programfiles%\\Microsoft Azure AD Connect Health Sync Agent\\Insights\\Microsoft.Identity.AadConnect.Health.AadSync.Host.exe"] = 2
  l_3_0["%programfiles%\\Huntress\\HuntressAgent.exe"] = 2
  l_3_0["%programfiles%\\vast limits\\uberAgent\\uberAgent.exe"] = 2
  l_3_0["%programfiles%\\Adobe\\Acrobat DC\\Acrobat\\AcroCEF\\AcroServicesUpdater.exe"] = 2
  l_3_0["%programfiles%\\Dell\\DellOptimizer\\DellOptimizer.exe"] = 2
  l_3_0["%programfiles%\\Manufacturer\\Endpoint Agent\\edpa.exe"] = 2
  l_3_0["%programfiles%\\CyberArk\\Endpoint Privilege Manager\\Agent\\vf_agent.exe"] = 2
  l_3_0["%programfiles%\\Morphisec\\bin\\ProtectorService64.exe"] = 2
  l_3_0["%programfiles%\\Zoom\\bin\\CptHost.exe"] = 2
  l_3_0["%programfiles%\\TOLLAD\\GEMONPROC.exe"] = 2
  l_3_0["%programfiles%\\SMS_CCM\\CcmExec.exe"] = 2
  l_3_0["%programfiles%\\HEAT Software\\EMSSAgent\\*\\lmhost.exe"] = 2
  l_3_0["%programfiles%\\Skyhigh\\SCP\\ScpService.exe"] = 2
  l_3_0["C:\\Packages\\Plugins\\Microsoft.Azure.Diagnostics.IaaSDiagnostics\\*\\Monitor\\x64\\MonAgentCore.exe"] = 0
  l_3_0["C:\\Packages\\Plugins\\Microsoft.Azure.Security.Monitoring.AzureSecurityWindowsAgent\\*\\Monitoring\\Agent\\Extensions\\AzureSecurityPack\\pmfexe.exe"] = 0
  l_3_0["C:\\eGurkha\\lib\\AppPid.exe"] = 0
  l_3_0["C:\\blp\\API\\Office Tools"] = 0
  l_3_0["C:\\blp\\Wintrv"] = 0
  l_3_0["%windir%\\System32\\DriverStore\\FileRepository\\hpanalyticscomp.*\\x64\\Provider Data Sources\\ProcInfo\\ProcInfo.exe"] = 2
  l_3_0["%windir%\\system32\\RtkAudUService64.exe"] = 2
  l_3_0["%windir%\\system32\\nvwmi64.exe"] = 2
  l_3_0["%windir%\\system32\\lpksetup.exe"] = 2
  l_3_0["%windir%\\system32\\LogonUI.exe"] = 2
  l_3_0["%windir%\\system32\\DriverStore\\FileRepository\\hpcustomcapcomp.inf_amd64_*\\x64\\AppHelperCap.exe"] = 2
  l_3_0["%windir%\\AdminArsenal\\PDQInventory-Scanner\\service-1\\PDQInventory-Scanner-1.exe"] = 2
  l_3_0["%windir%\\RtkBtManServ.exe"] = 2
  l_3_0["%windir%\\CarbonBlack\\cb.exe"] = 2
  l_3_0["%windir%\\LTSvc\\LTSVC.exe"] = 2
  l_3_0["%windir%\\CCM\\CcmExec.exe"] = 2
  l_3_0["%windir%\\CCM\\SensorLogonTask.exe"] = 2
  l_3_0["%windir%\\CCM\\SleepAgentService.exe"] = 2
  l_3_0["%windir%\\Sysmon64.exe"] = 2
  l_3_0["%windir%\\sysmon.exe"] = 2
  l_3_0["%windir%\\SysWOW64\\CCM\\CcmExec.exe"] = 2
  l_3_0["%windir%\\Temp\\Ctx-*\\Extract\\TrolleyExpress.exe"] = 2
  l_3_0["%programdata%\\Citrix\\Citrix Receiver*\\TrolleyExpress.exe"] = 2
  l_3_0["%programdata%\\Citrix\\Citrix Workspace *\\TrolleyExpress.exe"] = 2
  l_3_0["%programdata%\\App-V\\*\\*\\Root\\VFS\\Windows\\CCM\\CcmExec.exe"] = 2
  l_3_0["%programfiles(x86)%\\Citrix\\Citrix Workspace *\\TrolleyExpress.exe"] = 2
  l_3_0["%temp%\\Ctx-*\\Extract\\TrolleyExpress.exe"] = 1
  l_3_0["%programfiles%\\Quest\\ChangeAuditor\\Agent\\NPSrvHost.exe"] = 2
  l_3_0["%programfiles%\\Quest\\ChangeAuditor\\Service\\ChangeAuditor.Service.exe"] = 2
  l_3_0["%windir%\\system32\\DriverStore\\FileRepository\\hpqkbsoftwarecompnent.inf_amd64_*\\HotKeyServiceUWP.exe"] = 2
  l_3_0["%windir%\\system32\\CompatTelRunner.exe"] = 2
  l_3_0["%programfiles(x86)%\\Printer Properties Pro\\Printer Installer Client\\PrinterInstallerClient.exe"] = 2
  l_3_0["%programfiles%\\Printer Properties Pro\\Printer Installer Client\\PrinterInstallerClient.exe"] = 2
  l_3_0["%programfiles(x86)%\\Zscaler\\ZSATunnel\\ZSATunnel.exe"] = 2
  l_3_0["%programfiles%\\Zscaler\\ZSATunnel\\ZSATunnel.exe"] = 2
  l_3_0["%programfiles(x86)%\\ManageSoft\\Security Agent\\mgssecsvc.exe"] = 2
  l_3_0["%programfiles%\\ManageSoft\\Security Agent\\mgssecsvc.exe"] = 2
  l_3_0["%programfiles(x86)%\\Snow Software\\Inventory\\Agent\\snowagent.exe"] = 2
  l_3_0["%programfiles%\\Snow Software\\Inventory\\Agent\\snowagent.exe"] = 2
  l_3_0["c:\\windows\\system32\\WerFaultSecure.exe"] = 0
  l_3_0["c:\\windows\\system32\\wbem\\WmiPrvSE.exe"] = 0
  l_3_0["c:\\windows\\SysWOW64\\wbem\\WmiPrvSE.exe"] = 0
  l_3_0["\\Device\\HarddiskVolume?\\Windows\\System32\\svchost.exe"] = 0
  l_3_0["\\Device\\HarddiskVolume?\\Windows\\System32\\wbem\\wmiprvse.exe"] = 0
  l_3_0["%windir%\\system32\\fsiso.exe"] = 2
  return l_3_0
end

GetCommandLineExclusions = function()
  -- function num : 0_3
  local l_4_0 = "^\\\"?.:\\\\windows\\\\system32\\\\werfault\\.exe\\\"?((?!\\-s).)*$"
  local l_4_1 = {}
  l_4_1[l_4_0] = 0
  return l_4_1
end


